---@module 'lazy'
---@type LazySpec
return {
  'folke/which-key.nvim',
  lazy = false,
  priority = 900,
  config = function()
    require('which-key').setup {
      delay = function(ctx)
        if ctx.keys == '<space>' or ctx.prefix == '<space>' then
          return 200
        end
        return 500
      end,
      spec = {
        { 'gr', group = '󰒍 LSP Actions', mode = { 'n' } },
        { '<leader>e', desc = '󰈔 Oil (Parent Dir)' },
        { '<leader>fe', desc = '󰈔 File Explorer (nvim-tree)' },
        { '<leader>fr', desc = '󰈔 Reveal File in Tree' },
        { '<leader>b', group = '󰓩 Buffer' },
        { '<leader>bc', desc = '󰅖 Close Buffer' },
        { '<leader>bo', desc = '󰅗 Close Other Buffers' },
        { '<leader>ba', desc = '󰅘 Close All Buffers' },
        { '<leader>f', group = '󰈔 Find', mode = { 'n', 'v' } },
        { '<leader>ff', desc = '󰈔 Find Files', mode = { 'n', 'v' } },
        { '<leader>fg', desc = ' Find Git Files', mode = { 'n', 'v' } },
        { '<leader>fh', desc = ' Find Hidden/All Files', mode = { 'n', 'v' } },
        { '<leader>fl', desc = ' Find Recent Files', mode = { 'n', 'v' } },
        { '<leader>fn', desc = '󰒕 Find Neovim Config' },
        { '<leader>s', group = '󰍉 Search', mode = { 'n', 'v' } },
        { '<leader>u', group = '󰙵 UI' },
        { '<leader>ua', desc = '󰈬 Aerial (Code Outline)' },
        { '<leader>ud', desc = 'Toggle Diagnostics (Location List)' },
        { '<leader>uv', desc = 'Toggle Inline Diagnostics' },
        { '<leader>uu', desc = '󰕍 Undo Tree' },
        { '<leader>uz', desc = '󱓞 Zen Mode (Focus)' },
        { '<leader>t', group = ' Terminal' },
        { '<leader>t1', desc = ' Terminal 1 (Vertical)' },
        { '<leader>t2', desc = ' Terminal 2 (Horizontal)' },
        { '<leader>th', desc = ' Toggle Inlay [H]ints' },
        { '<leader>g', group = '  Git' },
        { '<leader>gg', desc = ' Git Status (Neogit)' },
        { '<leader>gc', desc = ' Git Commits (Telescope)' },
        { '<leader>gb', desc = ' Git Branches (Telescope)' },
        { '<leader>gd', desc = ' Git Diff (Diffview)' },
        { '<leader>gl', desc = ' Git Log (File History)' },
        { '<leader>gq', desc = ' Close Git (Neogit/Diffview)' },
        { '<leader>gx', desc = ' Force-close Diffview Buffers' },
        { '<leader>h', group = ' Harpoon' },
        { '<leader>ha', desc = ' Add Mark' },
        { '<leader>hm', desc = ' Menu' },
        { '<leader>h1', desc = '1️⃣ File 1' },
        { '<leader>h2', desc = '2️⃣ File 2' },
        { '<leader>h3', desc = '3️⃣ File 3' },
        { '<leader>h4', desc = '4️⃣ File 4' },
        { '<leader>hn', desc = ' Next' },
        { '<leader>hp', desc = ' Previous' },
        { '<leader>q', group = '󰔌 Session/Quit' },
        { '<leader>qs', desc = ' Save Session' },
        { '<leader>ql', desc = ' Load Session' },
        { '<leader>y', desc = ' Yank to Clipboard (+)', mode = { 'n', 'v' } },
        { '<leader>Y', desc = ' Yank Line to Clipboard (+)' },
        { '<leader>c', group = '📋 Clipboard' },
        { '<leader>ca', desc = ' Copy All (File)' },
        { '<leader>cf', desc = ' Copy File Path' },
        { '<leader>cl', desc = ' Copy Path:Line' },
        { '<leader>x', desc = 'Toggle Workspace Diagnostics (Quickfix)' },
      },
      win = {
        border = 'rounded',
        no_overlap = true,
        padding = { 1, 2 },
      },
      layout = {
        height = { min = 4, max = 25 },
        width = { min = 20, max = 50 },
        spacing = 3,
        align = 'left',
      },
      sort = { 'local', 'order' },
      plugins = {
        marks = true,
        registers = true,
        spelling = {
          enabled = true,
          suggestions = 20,
        },
        presets = {
          operators = true,
          motions = true,
          text_objects = true,
          windows = true,
          nav = true,
          z = true,
          g = true,
        },
      },
    }
  end,
}
