---@module 'lazy'
---@type LazySpec
return {
  'folke/which-key.nvim',
  lazy = false,
  priority = 900,
  config = function()
    require('which-key').setup {
      delay = 0,
      spec = {
        { 'gr', group = '󰒍 LSP Actions', mode = { 'n' } },
        { '<leader>e', desc = '󰈔 Toggle File Tree' },
        { '<leader>f', group = '󰈔 Find', mode = { 'n', 'v' } },
        { '<leader>ff', desc = '󰈔 Find Files', mode = { 'n', 'v' } },
        { '<leader>fg', desc = ' Find Git Files', mode = { 'n', 'v' } },
        { '<leader>fh', desc = ' Find Hidden Files', mode = { 'n', 'v' } },
        { '<leader>fn', desc = '󰒕 Find Neovim Config' },
        { '<leader>s', group = '󰍉 Search', mode = { 'n', 'v' } },
        { '<leader>u', group = '󰙵 UI' },
        { '<leader>ua', desc = '󰈬 Aerial (Code Outline)' },
        { '<leader>uz', desc = '󱓞 Zen Mode (Focus)' },
        { '<leader>t', group = ' Terminal' },
        { '<leader>t1', desc = ' Terminal 1 (Vertical)' },
        { '<leader>t2', desc = ' Terminal 2 (Horizontal)' },
        { '<leader>th', desc = ' Toggle Inlay [H]ints' },
        { '<leader>g', group = '  Git' },
        { '<leader>gg', desc = ' Git Status (Neogit)' },
        { '<leader>gf', desc = ' Git Files' },
        { '<leader>h', group = ' Harpoon' },
        { '<leader>ha', desc = ' Add Mark' },
        { '<leader>hm', desc = ' Menu' },
        { '<leader>h1', desc = '1️⃣ File 1' },
        { '<leader>h2', desc = '2️⃣ File 2' },
        { '<leader>h3', desc = '3️⃣ File 3' },
        { '<leader>h4', desc = '4️⃣ File 4' },
        { '<leader>hn', desc = ' Next' },
        { '<leader>hp', desc = ' Previous' },
        { '<leader>q', group = '󰔌 Session/Quit' },
        { '<leader>qs', desc = ' Save Session' },
        { '<leader>ql', desc = ' Load Session' },
        { '<leader>c', group = '📋 Clipboard' },
        { '<leader>cy', desc = ' Copy File/Selection' },
        { '<leader>cp', desc = ' Paste from Clipboard' },
        { '<leader>cL', desc = ' Copy Line' },
        { '<leader>cf', desc = ' Copy File Path' },
        { '<leader>cl', desc = ' Copy Path:Line' },
      },
      win = {
        border = 'rounded',
        no_overlap = true,
        padding = { 1, 2 },
      },
      layout = {
        height = { min = 4, max = 25 },
        width = { min = 20, max = 50 },
        spacing = 3,
        align = 'left',
      },
      sort = { 'local', 'order' },
      plugins = {
        marks = true,
        registers = true,
        spelling = {
          enabled = true,
          suggestions = 20,
        },
        presets = {
          operators = true,
          motions = true,
          text_objects = true,
          windows = true,
          nav = true,
          z = true,
          g = true,
        },
      },
    }
  end,
}
